#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm test
#find . -name 'coverage' -type d -prune -exec rm -rf '{}' +
pnpm build
#find . -name 'build' -type d -prune -exec rm -rf '{}' +  -o -name 'dist' -type d -prune -exec rm -rf '{}' +  -o -name '.next' -type d -prune -exec rm -rf '{}' +
